server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Redirige toutes les requêtes vers index.html (pour React Router si utilisé plus tard)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Configuration du cache pour les assets statiques
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
